; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocidad del Monitor Serie (Esencial para ver tus logs)
monitor_speed = 115200

; Velocidad de subida (Opcional: Hace que cargar el código sea más rápido)
upload_speed = 921600

; Librerías necesarias
lib_deps =
    ; Para manejar mensajes JSON (muy útil para enviar datos ordenados por MQTT)
    bblanchon/ArduinoJson @ ^7.0.0
    
    ; Para la comunicación MQTT (Esta es la que faltaba)
    knolleary/PubSubClient @ ^2.8
    